# Generated by Django 5.1 on 2024-08-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(upload_to='product/images/'),
        ),
    ]
