# Generated by Django 5.1 on 2024-08-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_product_featured_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gender',
            options={'verbose_name_plural': 'gender'},
        ),
        migrations.AlterModelOptions(
            name='size',
            options={'verbose_name_plural': 'sizes'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category/images'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='product/images/'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='Size',
        ),
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.CharField(max_length=2),
        ),
        migrations.AddField(
            model_name='product',
            name='Size',
            field=models.ManyToManyField(to='web.size'),
        ),
    ]
