# Generated by Django 5.1 on 2024-08-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_product_gender_category_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
