# Generated by Django 5.1 on 2024-08-29 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_category_is_deleted_alter_product_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Size',
            new_name='size',
        ),
    ]
