# Generated by Django 5.1 on 2024-09-19 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_alter_cartitem_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
    ]
